### ISSUE TITLE
The entire spider stops when a POST to the API failed

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-scrape#108]
When some URL crawled by the spider is send to the API and the API returned an error this happen:

`
2019-02-22 11:54:03 [urllib3.connectionpool] DEBUG: http://process.ocdskingfisher.opendataservices.coop:80 "POST /api/v1/submit/file/ HTTP/1.1" 500 291
2019-02-22 11:54:03 [colombia] WARNING: Failed to post [https://apiocds.colombiacompra.gov.co:8443/apiCCE2.0/rest/releases?page=34446]. API status code: 500
2019-02-22 11:54:03 [scrapy.core.scraper] DEBUG: Scraped from <200 https://apiocds.colombiacompra.gov.co:8443/apiCCE2.0/rest/releases?page=34446>
None
2019-02-22 11:54:03 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x7fc86ce2da90>>
Traceback (most recent call last):
  File "/home/ocdskfs/scrapyd/.ve/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/ocdskfs/scrapyd/.ve/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/ocdskfs/scrapyd/.ve/lib/python3.6/site-packages/scrapy/extensions/feedexport.py", line 247, in item_scraped
    slot.exporter.export_item(item)
  File "/home/ocdskfs/scrapyd/.ve/lib/python3.6/site-packages/scrapy/exporters.py", line 92, in export_item
    itemdict = dict(self._get_serialized_fields(item))
  File "/home/ocdskfs/scrapyd/.ve/lib/python3.6/site-packages/scrapy/exporters.py", line 66, in _get_serialized_fields
    field_iter = six.iterkeys(item)
  File "/home/ocdskfs/scrapyd/.ve/lib/python3.6/site-packages/six.py", line 581, in iterkeys
    return iter(d.keys(**kw))
AttributeError: 'NoneType' object has no attribute 'keys'
2019-02-22 11:54:03 [scrapy.core.engine] INFO: Closing spider (finished)
`

Finishing the entire spider without catching the error and without continuing with the next urls

**Comment by odscjames** [comment]
https://github.com/open-contracting/kingfisher-process/issues/112 will make the error recorded in the DB and a 200 response returned, so the spider will continue

**Comment by jpmckinney** [comment]
Presumably fixed by https://github.com/open-contracting/kingfisher-process/issues/113
